version: "3.8"

services:
  training_app:
    container_name: training_app
    image: training_app
    env_file:
      - .env
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - ./${LOCAL_APP_PATH}/scripts:/${PATH_APP_IN_DOCKER}/scripts
      - ./${LOCAL_APP_PATH}/backend_db:/${PATH_APP_IN_DOCKER}/backend_db
      - ./${LOCAL_APP_PATH}/training_app:/${PATH_APP_IN_DOCKER}/training_app
      - ./${LOCAL_APP_PATH}/tests:/${PATH_APP_IN_DOCKER}/tests
      - ./${LOCAL_APP_PATH}/main.py:/${PATH_APP_IN_DOCKER}/main.py
      - ./${LOCAL_APP_PATH}/poetry.lock:/${PATH_APP_IN_DOCKER}/poetry.lock
      - ./${LOCAL_APP_PATH}/pyproject.toml:/${PATH_APP_IN_DOCKER}/pyproject.toml
      - ./${LOCAL_APP_PATH}/README.md:/${PATH_APP_IN_DOCKER}/README.md
      - training_app_alembic_versions:/${PATH_APP_IN_DOCKER}/${APP_NAME}/alembic/versions
      - training_app_venv:/${PATH_APP_IN_DOCKER}/.venv
    ports:
      - 8000:8000
    depends_on:
      mssql_db:
        condition: service_healthy
    networks:
      - backend
  mssql_db:
    container_name: mssql_db
    hostname: ${DB_HOST}
    image: mssql_db
    env_file:
      - ./.env
    build:
      context: ./${LOCAL_APP_PATH}/backend_db/mssql/
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${DB_PORT}:1433
    volumes:
      - ${DOCKER_DATA_PATH}/config_mssql.log:/opt/app/config.log
      - mssql_data:/var/opt/mssql/
    networks:
      - backend
    healthcheck:
          test:
              [
                  "CMD-SHELL",
                  "/opt/mssql-tools/bin/sqlcmd -S ${DB_HOST} -U ${DB_USER} -P ${DB_PASSWORD} -Q 'SELECT 1' || exit 1"
              ]
          interval: 10s
          retries: 10
          start_period: 10s
          timeout: 3s
volumes:
  training_app_venv:
    driver_opts:
      o: bind
      type: none
      # TODO: Need to create a file file fastapi_training_app/.docker_data/backend/.venv/
      device: ${DOCKER_DATA_PATH}/.venv/
  training_app_alembic_versions:
    driver_opts:
      o: bind
      type: none
      # TODO: Need to create a file file fastapi_training_app/.docker_data/backend/alembic/versions/
      device: ${DOCKER_DATA_PATH}/alembic/versions/
  mssql_data:
    driver_opts:
      o: bind
      type: none
      # TODO: Need to create a file fastapi_training_app/.docker_data/backend/mssql_data: sudo chown -R 10001:0 fastapi_training_app/.docker_data
      device: ${DOCKER_DATA_PATH}/mssql_data/

networks:
  backend:
    name: backend
    driver: bridge